/**
 * InsightCard — one generated insight: a tinted icon, a short title, and engine-written body copy.
 *
 * Shared/reusable. `tone` drives the icon tint via semantic tokens (positive/neutral/caution) — it
 * is NOT a category color, so red/green only ever encode valence here. Body text is generated by
 * the insight engine and passed in; this component never authors copy.
 */
import type { LucideIcon } from 'lucide-react'
import './InsightCard.css'

export type InsightTone = 'positive' | 'neutral' | 'caution'

interface InsightCardProps {
  tone: InsightTone
  icon: LucideIcon
  title: string
  body: string
}

export default function InsightCard({ tone, icon: Icon, title, body }: InsightCardProps) {
  return (
    <div className={`insight-card insight-card--${tone}`}>
      <span className="insight-card__icon">
        <Icon size={30} strokeWidth={2} />
      </span>
      <div className="insight-card__text">
        <div className="insight-card__title">{title}</div>
        <p className="insight-card__body">{body}</p>
      </div>
    </div>
  )
}
